export type Character = 'lati' | 'lumi' | 'pipi'

export interface TarotCard {
  id: number
  nameEn: string
  nameKo: string
  keywords: string[]
  healingMessage: string
  character: Character // 주 등장 캐릭터
  characterMessages: {
    lati: string  // 따뜻하고 설레는 톤
    lumi: string  // 짧고 차분한 톤
    pipi: string  // 행동 묘사로만
  }
  colorTheme: 'coral' | 'purple' | 'gray'
  emoji: string
}

export const tarotCards: TarotCard[] = [
  {
    id: 0,
    nameEn: 'The Fool',
    nameKo: '바보',
    keywords: ['시작', '순수', '용기'],
    healingMessage: '지금 이 순간, 그냥 걸어가도 괜찮아요.',
    character: 'lati',
    characterMessages: {
      lati: '이 카드가 나왔다는 건, 새로운 시작이 기다리고 있다는 신호예요! 두려워도 한 발만 내딛어봐요 🌸',
      lumi: '...첫 걸음이에요. 알면서도 무서운 거, 당연해요.',
      pipi: '피피가 당신 발밑을 슬쩍 내려다보더니, 고개를 까딱합니다. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '🌱',
  },
  {
    id: 1,
    nameEn: 'The Magician',
    nameKo: '마법사',
    keywords: ['능력', '의지', '실현'],
    healingMessage: '당신에겐 이미 모든 게 있어요.',
    character: 'lati',
    characterMessages: {
      lati: '우와, 이 카드 나왔어요? 당신 안에 이미 모든 힘이 있다는 뜻이에요! 믿어봐요 ✨',
      lumi: '이미 갖고 있어요. 그걸 모르고 있을 뿐.',
      pipi: '피피가 두 날개를 살짝 펼쳤다 접습니다. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '✨',
  },
  {
    id: 2,
    nameEn: 'The High Priestess',
    nameKo: '여사제',
    keywords: ['직관', '내면', '신비'],
    healingMessage: '말하지 않아도 알고 있어요.',
    character: 'lumi',
    characterMessages: {
      lati: '이 카드는 내면의 목소리를 믿으라는 뜻이에요. 당신의 직감, 맞을 거예요 🌙',
      lumi: '...알고 있을 거예요. 말 안 해도.',
      pipi: '피피가 눈을 한 번 천천히 깜빡입니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '🌙',
  },
  {
    id: 3,
    nameEn: 'The Empress',
    nameKo: '여황제',
    keywords: ['풍요', '돌봄', '자연'],
    healingMessage: '오늘은 그냥 피어 있어도 돼요.',
    character: 'lati',
    characterMessages: {
      lati: '꽃이 억지로 피지 않듯이, 오늘은 그냥 있어도 충분해요. 당신 자체가 충분해요 🌺',
      lumi: '억지로 할 필요 없어요. 지금 이대로도.',
      pipi: '피피가 꽃집 한쪽에서 조용히 햇살을 맞고 있습니다. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '🌺',
  },
  {
    id: 4,
    nameEn: 'The Emperor',
    nameKo: '황제',
    keywords: ['주도권', '결단', '안정'],
    healingMessage: '한 번만 먼저 가도 괜찮아요.',
    character: 'lumi',
    characterMessages: {
      lati: '먼저 움직이는 게 무서운 거 알아요. 그래도 한 발만 먼저 가봐요. 잘 될 거예요 💪',
      lumi: '결정해요. 기다리다 보면 기회가 지나가요.',
      pipi: '피피가 자리에서 일어나 앞쪽으로 한 걸음 걷습니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '👑',
  },
  {
    id: 5,
    nameEn: 'The Hierophant',
    nameKo: '교황',
    keywords: ['지혜', '전통', '스승'],
    healingMessage: '당신 곁에 오래된 지혜가 있어요.',
    character: 'lumi',
    characterMessages: {
      lati: '주변에 믿을 수 있는 사람이 있어요. 혼자 다 하려 하지 말고, 도움받아도 괜찮아요 🤝',
      lumi: '가르침을 받을 시기예요. 혼자가 아니에요.',
      pipi: '피피가 꾸벅 90도로 고개를 숙입니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '📚',
  },
  {
    id: 6,
    nameEn: 'The Lovers',
    nameKo: '연인',
    keywords: ['사랑', '선택', '연결'],
    healingMessage: '당신에게 필요한 카드는, 연인이에요.',
    character: 'lati',
    characterMessages: {
      lati: '이 카드가 나왔어요! 사랑이든 선택이든, 마음이 이끄는 대로 가봐요. 틀리지 않을 거예요 💕',
      lumi: '...선택의 시간이에요. 마음이 이미 알고 있을 거예요.',
      pipi: '피피가 라티와 루미 사이 딱 중간에 앉습니다. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '💕',
  },
  {
    id: 7,
    nameEn: 'The Chariot',
    nameKo: '전차',
    keywords: ['전진', '의지', '극복'],
    healingMessage: '두려워도 앞으로.',
    character: 'lati',
    characterMessages: {
      lati: '무서워도 괜찮아요. 그 무서운 마음 안고 그냥 가는 거예요. 당신 할 수 있어요! 🚀',
      lumi: '멈추지 마요. 지금이 그 순간이에요.',
      pipi: '피피가 날개를 한 번 탁 치고 앞을 쳐다봅니다. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '⚡',
  },
  {
    id: 8,
    nameEn: 'Strength',
    nameKo: '힘',
    keywords: ['내면의 힘', '인내', '용기'],
    healingMessage: '오늘도 문 열었다는 게, 충분해요.',
    character: 'lati',
    characterMessages: {
      lati: '오늘 하루 버텨낸 것만으로도 대단한 거예요. 정말로요. 충분히 잘하고 있어요 🌸',
      lumi: '오늘 여기까지 온 것만으로도. 충분해요.',
      pipi: '피피가 당신 옆에 조용히 와서 앉습니다. 아무 말 없이. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '🌸',
  },
  {
    id: 9,
    nameEn: 'The Hermit',
    nameKo: '은둔자',
    keywords: ['고독', '내면 탐구', '성찰'],
    healingMessage: '혼자인 시간이 당신을 채우고 있어요.',
    character: 'lumi',
    characterMessages: {
      lati: '혼자인 시간이 무서울 수 있어요. 그런데 그 시간이 나중에 다 빛이 돼요. 지금 괜찮아요 🌙',
      lumi: '혼자여도 괜찮아요. 채워지는 시간이에요.',
      pipi: '피피가 달빛 아래 혼자 편의점 앞에 앉아있습니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '🕯️',
  },
  {
    id: 10,
    nameEn: 'Wheel of Fortune',
    nameKo: '운명의 수레바퀴',
    keywords: ['변화', '순환', '전환'],
    healingMessage: '흐름이 바뀌고 있어요.',
    character: 'pipi',
    characterMessages: {
      lati: '무언가 달라지려 하고 있어요! 이 변화, 좋은 방향으로 가고 있을 거예요 🌀',
      lumi: '흐름이 바뀌어요. 저항하지 않아도 돼요.',
      pipi: '피피가 자리를 이동합니다. 정해진 방향은 없지만, 움직이고 있어요. 🕊️',
    },
    colorTheme: 'gray',
    emoji: '🌀',
  },
  {
    id: 11,
    nameEn: 'Justice',
    nameKo: '정의',
    keywords: ['균형', '인과', '공정'],
    healingMessage: '받아야 할 것들이 오고 있어요.',
    character: 'lumi',
    characterMessages: {
      lati: '노력한 게 헛되지 않아요. 받아야 할 것들이 오는 중이에요. 조금만 더요 ⚖️',
      lumi: '균형이 맞아지고 있어요. 때가 있어요.',
      pipi: '피피가 천천히 고개를 까딱합니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '⚖️',
  },
  {
    id: 12,
    nameEn: 'The Hanged Man',
    nameKo: '매달린 사람',
    keywords: ['정지', '새로운 시각', '기다림'],
    healingMessage: '지금 멈추는 것도 움직임이에요.',
    character: 'pipi',
    characterMessages: {
      lati: '지금 멈춰있는 것 같아도 괜찮아요. 기다리는 것도 움직이는 거예요. 시간이 알아서 해줄 거예요 ⏸️',
      lumi: '멈춤이에요. 다른 방향을 볼 기회.',
      pipi: '피피가 거꾸로 매달린 것처럼 고개를 아래로 향하고 있습니다. 🕊️',
    },
    colorTheme: 'gray',
    emoji: '⏸️',
  },
  {
    id: 13,
    nameEn: 'Death',
    nameKo: '죽음',
    keywords: ['변환', '끝과 시작', '전환'],
    healingMessage: '끝나야 시작될 수 있어요.',
    character: 'pipi',
    characterMessages: {
      lati: '무서운 이름이지만 괜찮아요! 이 카드는 끝이 아니라 새로운 시작을 뜻해요. 변화가 오고 있어요 🌿',
      lumi: '끝이 아니에요. 다른 형태로 시작되는 거예요.',
      pipi: '피피가 계절이 바뀌는 하늘을 가만히 올려다봅니다. 🕊️',
    },
    colorTheme: 'gray',
    emoji: '🌿',
  },
  {
    id: 14,
    nameEn: 'Temperance',
    nameKo: '절제',
    keywords: ['조화', '균형', '절제'],
    healingMessage: '지금 이 균형, 오래오래 있었으면 해요.',
    character: 'lati',
    characterMessages: {
      lati: '지금 이 순간이 딱 좋아요. 너무 서두르지 말고, 이 좋은 느낌 즐겨봐요 ✨',
      lumi: '지금 이대로도 충분해요. 조화로운 순간이에요.',
      pipi: '피피가 라티와 루미 사이에서 음료를 조용히 쳐다봅니다. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '🍵',
  },
  {
    id: 15,
    nameEn: 'The Devil',
    nameKo: '악마',
    keywords: ['집착', '속박', '해방'],
    healingMessage: '놓아버려도 괜찮아요.',
    character: 'lumi',
    characterMessages: {
      lati: '놓아버리기 무서운 거 알아요. 그런데 쥐고 있는 게 아파진다면, 한 번 내려놓아봐요 💜',
      lumi: '...놓아요. 붙잡고 있는 게 오히려 무거워지고 있어요.',
      pipi: '피피가 밴드를 한 번 만져보더니, 그냥 내려놓습니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '🔓',
  },
  {
    id: 16,
    nameEn: 'The Tower',
    nameKo: '탑',
    keywords: ['붕괴', '충격', '재건'],
    healingMessage: '무너져야 새로 지을 수 있어요.',
    character: 'pipi',
    characterMessages: {
      lati: '지금 힘든 것 알아요. 그런데 무너진 자리에서만 새것을 지을 수 있어요. 당신 할 수 있어요 ⚡',
      lumi: '무너지는 건 끝이 아니에요. 새로 짓는 준비예요.',
      pipi: '피피가 흔들리는 꽃집을 멀리서 가만히 바라봅니다. 🕊️',
    },
    colorTheme: 'gray',
    emoji: '⚡',
  },
  {
    id: 17,
    nameEn: 'The Star',
    nameKo: '별',
    keywords: ['희망', '치유', '빛'],
    healingMessage: '당신은 이미 충분히 빛나고 있어요.',
    character: 'lumi',
    characterMessages: {
      lati: '별 카드가 나왔어요! 이건 희망이 있다는 신호예요. 당신은 이미 충분히 빛나고 있어요 ⭐',
      lumi: '...빛나고 있어요. 본인만 모르는 거예요.',
      pipi: '피피가 루미의 카메라 속 별 사진을 슬며시 봅니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '⭐',
  },
  {
    id: 18,
    nameEn: 'The Moon',
    nameKo: '달',
    keywords: ['혼란', '무의식', '방황'],
    healingMessage: '헤매도 돼요. 달이 있으니까.',
    character: 'pipi',
    characterMessages: {
      lati: '길을 잃은 것 같아도 괜찮아요. 달이 있으면 어두워도 걸을 수 있어요. 지금 헤매도 돼요 🌙',
      lumi: '헤매는 것도 답을 찾는 과정이에요.',
      pipi: '피피가 새벽 편의점 앞에 혼자 앉아, 달을 올려다봅니다. 🕊️',
    },
    colorTheme: 'gray',
    emoji: '🌙',
  },
  {
    id: 19,
    nameEn: 'The Sun',
    nameKo: '태양',
    keywords: ['기쁨', '충만', '성공'],
    healingMessage: '오늘 하루가, 전부예요.',
    character: 'lati',
    characterMessages: {
      lati: '오늘이 정말 좋은 날이 될 것 같은 느낌, 저도 나요! 이 좋은 에너지 마음껏 누려요 ☀️',
      lumi: '오늘이에요. 지금이 제일 좋은 순간이에요.',
      pipi: '피피가 셋 중에서 가장 환한 자리에 앉아있습니다. 🕊️',
    },
    colorTheme: 'coral',
    emoji: '☀️',
  },
  {
    id: 20,
    nameEn: 'Judgement',
    nameKo: '심판',
    keywords: ['깨달음', '부름', '응답'],
    healingMessage: '이제 말해도 돼요.',
    character: 'lumi',
    characterMessages: {
      lati: '마음속에 하고 싶었던 말이 있죠? 이제 말해도 돼요. 준비됐어요, 당신 🌟',
      lumi: '...말할 때가 됐어요. 더 이상 미루지 않아도 돼요.',
      pipi: '피피가 루미 쪽을 가만히 바라봅니다. 🕊️',
    },
    colorTheme: 'purple',
    emoji: '🌟',
  },
  {
    id: 21,
    nameEn: 'The World',
    nameKo: '세계',
    keywords: ['완성', '성취', '통합'],
    healingMessage: '여기까지 온 당신에게, 수고했어요.',
    character: 'pipi',
    characterMessages: {
      lati: '해냈어요! 이 카드는 완성의 카드예요. 여기까지 온 당신, 정말 수고 많았어요 🌍',
      lumi: '여기까지 왔네요. ...수고했어요.',
      pipi: '피피가 라티, 루미와 나란히 서서 저 멀리 노을을 바라봅니다. 🕊️',
    },
    colorTheme: 'gray',
    emoji: '🌍',
  },
]

export const characters = {
  lati: {
    id: 'lati' as Character,
    name: '라티',
    nameEn: 'Lati',
    species: '핑크 토끼 🐰',
    job: '꽃집 플로리스트',
    color: '#FFB3A7',
    bgGradient: 'from-pink-200 via-rose-100 to-orange-100',
    cardBg: 'bg-rose-50',
    description: '따뜻하고 설레는 마음으로 안내해드릴게요.',
    emoji: '🌸',
    tone: '설레고 따뜻한 톤',
  },
  lumi: {
    id: 'lumi' as Character,
    name: '루미',
    nameEn: 'Lumi',
    species: '보라 고양이 🐱',
    job: '필름 사진작가',
    color: '#7B5EA7',
    bgGradient: 'from-purple-200 via-violet-100 to-indigo-100',
    cardBg: 'bg-violet-50',
    description: '...조용히, 핵심만 말해드릴게요.',
    emoji: '📷',
    tone: '짧고 차분한 톤',
  },
  pipi: {
    id: 'pipi' as Character,
    name: '피피',
    nameEn: 'Pipi',
    species: '회색 비둘기 🕊️',
    job: '???',
    color: '#9EA3B0',
    bgGradient: 'from-slate-200 via-gray-100 to-zinc-100',
    cardBg: 'bg-slate-50',
    description: '(말 없이 당신 곁에 있어드릴게요.)',
    emoji: '🕊️',
    tone: '행동으로만',
  },
}

export type SpreadMode = 'single' | 'three'

export function drawCards(count: number): TarotCard[] {
  const shuffled = [...tarotCards].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
